services:
  - type: web
    name: my-flower-app
    env: node
    buildCommand: cd client && npm install && npm run build && cd .. && npm install
    startCommand: node ./bin/www
    envVars:
      - key: NODE_VERSION
        value: 18
