services:
  - type: web
    name: my-flower-app
    env: node
    buildCommand: npm flower0 && npm install && npm run build && cd ../flower0express && npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
